DROP TABLE IF EXISTS experts;

CREATE TABLE experts (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    name TEXT NOT NULL,
    curl TEXT NOT NULL
);
